### ISSUE TITLE
Not parsing token properly?

### ISSUE THREAD

**Issue by dhanson358** [swelham/ueberauth_microsoft#7]
I'm having an odd issue with the `fetch_user/2` portion of the app.  It seems like I get my OAuth2 tokens just fine, but when trying to fetch the user data from `https://graph.microsoft.com/v1.0/me`, it's trying to pass a JSON representation of the token instead of the token itself.  Turning on OAuth2's debug logging, I'm getting something like this:

```
[debug]   OAuth2 Provider Request
  url: "https://graph.microsoft.com/v1.0/me/"
  method: :get
  headers: [{"accept", "application/json"}, {"authorization", "Bearer {\"token_type\":\"Bearer\",\"scope\":\"email openid profile https://graph.microsoft.com/Calendars.Read https://graph.microsoft.com/User.Read\",\"expires_in\":3599,\"ext_expires_in\":3599,\"access_token\":\"eyJ0eXAiOiJKV1QiLCJub25jZSI6Ik02N...\", \"refresh_token\":\"OAQABAAAAAAAP0wLl...\", \"id_token\": "eyJ0eXAiO..."}]
  body: ""
  req_opts: [ssl_options: [versions: [:"tlsv1.2"]]]
```

This results in an error from the MS Graph API along the lines of `CompactToken parsing failed with error code: 80049217`

If I extract the "access_token" string from this JSON and manually pass it as a bearer token via CURL, everything works, so I know the token is valid.

What's perplexing to me is why is that "Bearer" in the `OAuth2.Client.get` (in `ueberauth/strategy/microsoft.ex#105`) passing an whole stringified-JSON instead of just the plain ASCII access token?  

It seems "show stopping" enough that I'm wondering if I have some odd configuration causing this issues, but it seems like a pretty simple setup so I'm not sure what I could have done wrong. 

Appreciate any advice.

**Comment by swelham** [comment]
Thank you for raising this issue.

I have spent some time looking into this and I am able to reproduce the error you are seeing. It turns out this is a show stopper bug and one that I haven't come across because the apps I have using this library haven't been updated in a while.

The problem is this library is built against an older version of the ueberauth and oauth2 libraries. The latest versions require a serializer to be configured on the oatuh client which is relied upon when decoding the payload returned by the oauth provider. I'm not sure how I missed this breaking change but somehow that happened.

The good news is, I have a fix that will bring the ueberauth version up to `~> 0.6` and configure the serializer correctly.

**Comment by swelham** [comment]
This is now published to hex.

Please try updating you mix deps to `{:ueberauth_microsoft, "~> 0.6.0"}` and let me know if you have any further issues.

**Comment by dhanson358** [comment]
Works great now, thank you very much!
